#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>
#include <math.h>

void swap(double* a, double* b){
  double t = *a;
  *a = *b;
  *b = t;
}

int partition(double *arr, int low, int high){
  int pivot = arr[high];
  int i = low - 1;

  for(int j = low; j <= high - 1; j++) {
    if (arr[j] < pivot) {
      i++;
      swap(&arr[i], &arr[j]);
    }
  }
  swap(&arr[i + 1], &arr[high]);
  return (i + 1);
}

void quickSort(double *arr, int low, int high){
  if (low < high) {
    int p = partition(arr, low, high);
    quickSort(arr, low, p - 1);
    quickSort(arr, p + 1, high);
  }
}


input_data * sort_1(input_data *input, CLIENT *client) 
  {

  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */
  input_data* dp = input;

  quickSort(dp->input_data.input_data_val,0,dp->input_data.input_data_len - 1);

  return dp;
}

/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */
 
input_data * sort_1_svc(input_data *input, struct svc_req *svc) 
  {
  CLIENT *client;
  return( sort_1( input, client) );
  }
